---
title: "Electronic Health Records: Who Uses It?"
author: "Katherine Wang, Eunice Yeh, Lauren Yoo"
output: html_document
---

```{r, echo=FALSE}
library("htmltools")
library("vembedr")
embed_url("https://www.youtube.com/watch?v=vn9mMeWcgoM")
```



### Background and Motivation

In the past 10 years, there has been a lot of discussion around the benefits and risks of adopting electronic health records (EHR's). Many news sources have covered the topic, and multiple government agencies have published recommendations and articles on the adoption of EHR's. From 2008 to 2015, the number of office-based practitioners with EHR systems doubled, proving that the popularity of EHR's are only increasing [(Healthit.gov)](https://dashboard.healthit.gov/quickstats/pages/physician-ehr-adoption-trends.php).

In 2011, the Centers for Medicare & Medicaid Services (CMS) initiated the Medicare and Medicaid Electronic Health Record Incentive Programs to encourage medical professionals to adopt EHR technology. The program includes incentives for different stages of implementation, including establishing EHR requirements, demonstrating meaningful use, and a final stage to demonstrate improved health outcomes that will start this year (2017).


### Project Objectives

We looked at hospital and physician level data from 2016 to see if there might be some similar characteristics of healthcare providers who are and are not adopting EHR use. Since EHR's are a technology-based implementation, our group wanted to see if younger physicans are more likely to adopt EHR technology. What are some of the factors that might be associated with adoptation of EHR's? Additionally, we know that physicians working in hospitals do not have a choice in adopting EHR's. As a result, we wanted to see if there were hospital-related factors affecting adoption of EHRs. 

To qualify for the incentive program, participants in the program need to use certified EHR technology as recognized by CMS. This can include a comprehensive package offered by one vendor or different modules or products offered by different vendors. All must be certified, but practitioners have some choice in implementation. As a result, we also thought it might be interesting to see how vendors and products are distributed among the EHR users.

We also hoped to gain some insight to see if there were any differences in trends across the United States - are the factors correlated with adoption of EHR's consistent across the country? Or are just a few states leading the pack?

The following terms were defined as follows by the Office of the National Coordinator for Health Information Technology:

> * Physicians adopted a Basic EHR if they reported their practice performed all of the following computerized functions: patient demographics, patient problem lists, electronic lists of medications taken by patients, clinician notes, orders for medications, viewing laboratory results, and viewing imaging results. The core capabilities of a Basic EHR were defined by DesRoches, et al. in the 2008 manuscript.
> * Any EHR system is a medical or health record system that is either all or partially electronic, and excludes systems solely for billing.
> * Data include non-federal, office-based physicians, and exclude radiologists, anesthesiologists, and pathologists.
> * A certified EHR system is one that meets the requirements adopted by the US Department of Health and Human Services.


### Conclusions
Ultimately, we found that a physician's gender and years since graduation were significantly correlated to use of Electronic Health Records. The odds of adopting EHR's were higher for males than they were for females, and the odds of adopting EHR's increased as the years since graduation increased. Note: we used years since graduation as an indicator of physician age.

On the hospital level, we did not find any factors that significantly affected EHR usage. We found that the information we had on hospitals were often highly correlated with each other, which made it hard to find any significant patterns.

In our secondary analysis, we found that many vendors were specialized and were only used by certain types of physicians. Practitioners in eye care had the highest EHR adoption rates, and a couple of the most popular vendors also seemed to offer products specifically for optometrists and opthalmologists. 


#### For more detailed information regarding our analysis, please see the following links:

* Our data and code can be found in our project GitHub, available [here](https://euniceyeh.github.io/EHR-Project/work.html) and [here](https://github.com/euniceyeh/EHR-Project)
* Screencast available [here]() *add link!!!!*

#### References:

Office of the National Coordinator for Health Information Technology. 'Office-based Physician Electronic Health Record Adoption,' Health IT Quick-Stat #50. dashboard.healthit.gov/quickstats/pages/physician-ehr-adoption-trends.php. December 2016.
